[package]
name = "debil-mysql"
version = "0.1.0"
authors = ["myuon <ioi.joi.koi.loi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
debil = { git = "https://github.com/myuon/debil.git" }
mysql_async = "0.21.1"
futures = "0.3.1"
tokio = { version = "0.2.9", features = ["rt-core"] }
failure = "0.1.6"
