[package]
name = "debil-mysql"
version = "0.1.0"
authors = ["myuon <ioi.joi.koi.loi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
debil = { git = "https://github.com/myuon/debil.git" }
mysql_async = "0.21.0-alpha.4"
futures-preview = { version = "=0.3.0-alpha.19", features = ["io-compat"] }
tokio = "0.2.0-alpha.6"
failure = "0.1.6"
